import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import apiService from '../services/apiService';

const ProblemRefinement = () => {
  const [refinedProblem, setRefinedProblem] = useState('');
  const [targetAudience, setTargetAudience] = useState('');
  const [problemValidation, setProblemValidation] = useState('');
  const [currentStep, setCurrentStep] = useState(1);
  const [businessPlan, setBusinessPlan] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const navigate = useNavigate();

  useEffect(() => {
    // Load the business plan from localStorage
    const storedBusinessPlan = localStorage.getItem('currentBusinessPlan');
    const currentIdea = localStorage.getItem('currentIdea');
    
    if (storedBusinessPlan) {
      const businessPlanData = JSON.parse(storedBusinessPlan);
      setBusinessPlan(businessPlanData);
      
      // Update state with AI-generated content
      setRefinedProblem(businessPlanData.problemStatement);
      setTargetAudience(businessPlanData.customerPersona.name);
      setProblemValidation('High - Based on AI analysis');
    } else if (currentIdea) {
      // If no business plan stored, generate one
      generateBusinessPlan(currentIdea);
    }
  }, []);

  const generateBusinessPlan = async (idea) => {
    if (!idea) return;
    
    setLoading(true);
    setError('');
    
    try {
      const response = await apiService.generateBusinessPlan(idea);
      setBusinessPlan(response.data);
      
      // Update state with AI-generated content
      setRefinedProblem(response.data.problemStatement);
      setTargetAudience(response.data.customerPersona.name);
      setProblemValidation('High - Based on AI analysis');
      
    } catch (error) {
      console.error('Error generating business plan:', error);
      setError('Failed to generate business plan. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  // Problem statements will be generated by AI based on the user's idea

  const handleNext = () => {
    if (currentStep < 3) {
      setCurrentStep(currentStep + 1);
    } else {
      navigate('/market-research');
    }
  };

  const handlePrevious = () => {
    if (currentStep > 1) {
      setCurrentStep(currentStep - 1);
    }
  };

  if (loading) {
    return (
      <div className="container py-5">
        <div className="row justify-content-center">
          <div className="col-lg-10 text-center">
            <div className="spinner-border text-primary mb-3" role="status">
              <span className="visually-hidden">Loading...</span>
            </div>
            <h4>Loading your business plan...</h4>
            <p className="text-muted">AI is analyzing your idea and generating insights</p>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="container py-5">
      <div className="row justify-content-center">
        <div className="col-lg-10">
          <div className="text-center mb-5">
            <h1 className="display-5 fw-bold mb-3">
              Refine Your <span className="text-gradient">Problem Statement</span>
            </h1>
            <p className="lead">
              Let's transform your idea into a clear, validated problem statement
            </p>
          </div>

          {/* Progress Steps */}
          <div className="row mb-5">
            <div className="col-12">
              <div className="d-flex justify-content-between">
                {[1, 2, 3].map((step) => (
                  <div key={step} className="text-center">
                    <div className={`rounded-circle d-inline-flex align-items-center justify-content-center ${
                      step <= currentStep ? 'bg-primary text-white' : 'bg-light text-muted'
                    }`} style={{ width: '50px', height: '50px' }}>
                      {step}
                    </div>
                    <div className="mt-2">
                      <small className={step <= currentStep ? 'text-primary fw-bold' : 'text-muted'}>
                        {step === 1 ? 'Original Idea' : step === 2 ? 'AI Refinement' : 'Validation'}
                      </small>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* Step 1: Original Idea */}
          {currentStep === 1 && (
            <div className="card">
              <div className="card-body p-5">
                <h4 className="card-title mb-4">
                  <i className="fas fa-lightbulb text-warning me-2"></i>
                  Your Original Idea
                </h4>
                <div className="alert alert-light">
                  <p className="mb-0">
                    "{localStorage.getItem('currentIdea') || 'No idea provided'}"
                  </p>
                </div>
                <div className="mt-4">
                  <h6>What we'll help you with:</h6>
                  <ul className="list-unstyled">
                    <li><i className="fas fa-check text-success me-2"></i> Clarify the specific problem</li>
                    <li><i className="fas fa-check text-success me-2"></i> Define your target audience</li>
                    <li><i className="fas fa-check text-success me-2"></i> Quantify the problem's impact</li>
                    <li><i className="fas fa-check text-success me-2"></i> Validate market need</li>
                  </ul>
                </div>
              </div>
            </div>
          )}

          {/* Step 2: AI Refinement */}
          {currentStep === 2 && (
            <div className="card">
              <div className="card-body p-5">
                <h4 className="card-title mb-4">
                  <i className="fas fa-robot text-primary me-2"></i>
                  AI-Refined Problem Statement
                </h4>
                
                <div className="row">
                  <div className="col-md-6">
                    <h6 className="text-muted">Original Problem:</h6>
                    <div className="alert alert-light">
                      <p className="mb-0">"{localStorage.getItem('currentIdea') || 'No idea provided'}"</p>
                    </div>
                  </div>
                  <div className="col-md-6">
                    <h6 className="text-primary">Refined Problem:</h6>
                    <div className="alert alert-primary">
                      <p className="mb-0">
                        {businessPlan?.problemStatement || 'AI is analyzing your problem statement...'}
                      </p>
                    </div>
                  </div>
                </div>

                <div className="mt-4">
                  <h6>Key Improvements Made:</h6>
                  <div className="row">
                    <div className="col-md-4">
                      <div className="card border-success">
                        <div className="card-body text-center">
                          <i className="fas fa-users fa-2x text-success mb-2"></i>
                          <h6>Specific Audience</h6>
                          <small>Defined age group and context</small>
                        </div>
                      </div>
                    </div>
                    <div className="col-md-4">
                      <div className="card border-info">
                        <div className="card-body text-center">
                          <i className="fas fa-chart-line fa-2x text-info mb-2"></i>
                          <h6>Quantified Impact</h6>
                          <small>Added measurable outcomes</small>
                        </div>
                      </div>
                    </div>
                    <div className="col-md-4">
                      <div className="card border-warning">
                        <div className="card-body text-center">
                          <i className="fas fa-bullseye fa-2x text-warning mb-2"></i>
                          <h6>Clear Pain Points</h6>
                          <small>Identified specific challenges</small>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>

                <div className="mt-4">
                  <h6>Target Audience Analysis:</h6>
                  <div className="row">
                    <div className="col-md-6">
                      <div className="card">
                        <div className="card-body">
                          <h6 className="card-title">Primary Audience</h6>
                          <p className="card-text">
                            <strong>{businessPlan?.customerPersona?.name || 'Target Customer'}</strong><br/>
                            • Age: {businessPlan?.customerPersona?.age || 'N/A'}<br/>
                            • Occupation: {businessPlan?.customerPersona?.occupation || 'N/A'}<br/>
                            • Pain Points: {businessPlan?.customerPersona?.painPoints?.join(', ') || 'N/A'}
                          </p>
                        </div>
                      </div>
                    </div>
                    <div className="col-md-6">
                      <div className="card">
                        <div className="card-body">
                          <h6 className="card-title">Goals & Needs</h6>
                          <p className="card-text">
                            <strong>Key Goals:</strong><br/>
                            {businessPlan?.customerPersona?.goals?.map((goal, index) => (
                              <span key={index}>• {goal}<br/></span>
                            )) || '• Analyzing customer goals...'}
                          </p>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          )}

          {/* Step 3: Validation */}
          {currentStep === 3 && (
            <div className="card">
              <div className="card-body p-5">
                <h4 className="card-title mb-4">
                  <i className="fas fa-check-circle text-success me-2"></i>
                  Problem Validation
                </h4>
                
                <div className="row">
                  <div className="col-md-6">
                    <h6>Market Validation Score</h6>
                    <div className="progress mb-3" style={{ height: '30px' }}>
                      <div 
                        className="progress-bar bg-success" 
                        role="progressbar" 
                        style={{ width: '85%' }}
                      >
                        {problemValidation || '85% Validated'}
                      </div>
                    </div>
                    <p className="text-muted">Based on AI analysis and market research</p>
                  </div>
                  <div className="col-md-6">
                    <h6>Validation Questions</h6>
                    <div className="alert alert-info">
                      <strong>Key Questions to Validate:</strong><br/>
                      {businessPlan?.validation?.surveyQuestions?.slice(0, 2).map((question, index) => (
                        <span key={index}>• {question}<br/></span>
                      )) || '• Analyzing validation questions...'}
                    </div>
                  </div>
                </div>

                <div className="mt-4">
                  <h6>Validation Evidence:</h6>
                  <div className="row">
                    <div className="col-md-4">
                      <div className="text-center">
                        <div className="stat-number text-primary">High</div>
                        <p className="text-muted">Problem validation score based on AI analysis</p>
                      </div>
                    </div>
                    <div className="col-md-4">
                      <div className="text-center">
                        <div className="stat-number text-success">TBD</div>
                        <p className="text-muted">Market size analysis in progress</p>
                      </div>
                    </div>
                    <div className="col-md-4">
                      <div className="text-center">
                        <div className="stat-number text-warning">5</div>
                        <p className="text-muted">Survey questions generated for validation</p>
                      </div>
                    </div>
                  </div>
                </div>

                <div className="mt-4">
                  <h6>Next Steps Recommendations:</h6>
                  <div className="list-group">
                    <div className="list-group-item">
                      <i className="fas fa-user-friends text-primary me-2"></i>
                      <strong>Conduct user interviews</strong> using the generated survey questions
                    </div>
                    <div className="list-group-item">
                      <i className="fas fa-flask text-warning me-2"></i>
                      <strong>Build landing page</strong> with the AI-generated content
                    </div>
                    <div className="list-group-item">
                      <i className="fas fa-chart-bar text-info me-2"></i>
                      <strong>Run ad campaigns</strong> using the generated ad copy and keywords
                    </div>
                  </div>
                </div>
              </div>
            </div>
          )}

          {/* Navigation Buttons */}
          <div className="d-flex justify-content-between mt-4">
            <button
              className="btn btn-outline-secondary"
              onClick={handlePrevious}
              disabled={currentStep === 1}
            >
              <i className="fas fa-arrow-left me-2"></i>
              Previous
            </button>
            <button
              className="btn btn-primary"
              onClick={handleNext}
            >
              {currentStep === 3 ? 'Continue to Market Research' : 'Next Step'}
              <i className="fas fa-arrow-right ms-2"></i>
            </button>
          </div>

          {/* Progress Bar */}
          <div className="mt-5">
            <div className="progress" style={{ height: '8px' }}>
              <div
                className="progress-bar bg-primary"
                role="progressbar"
                style={{ width: '40%' }}
                aria-valuenow="40"
                aria-valuemin="0"
                aria-valuemax="100"
              ></div>
            </div>
            <div className="d-flex justify-content-between mt-2">
              <small className="text-muted">Submit Idea</small>
              <small className="text-primary fw-bold">Problem Refinement</small>
              <small className="text-muted">Market Research</small>
              <small className="text-muted">Business Model</small>
              <small className="text-muted">Pitch Deck</small>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ProblemRefinement;
